# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 179a006073a987f80122f0e68277087e565f99c0da7a9607eb4c0295ad8cd30c89064f29386221e26edaa7909696743a271ee01a3377112fca82094868ea28db

test:
  secret_key_base: 4166d9f08984d285053be49eb9ab33b73398c424886abe09803ab6e89b6b56126dc850ad22028d5bfc83918e5d0a24c6c8c5dbc048740b151f28e4603636ad89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
